version: '3.5'
services:
  api:
    build: app
    volumes:
      - ./app:/usr/src/app
    networks:
      - server
    external_links:
      - client
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - db

  db:
    build: ./db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: password
    ports:
      - 3307

networks:
  server:
    external: true
