version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
  api: # The name of the service
    build: ./src # Location of our Dockerfile
    volumes: # Volume binding
      - ./src:/usr/src/app
    networks:
      - server
    external_links:
      - client
    ports:
      - 3000:3000 # Port mapping
    command: npm run start
    depends_on:
      - db

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306
      - 33060

#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - '8080:80'
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: password
#    networks:
#      - server

networks:
  server:
    external: true
