version: '3.5'
services:
  api:
    build: app
    volumes:
      - ./app:/usr/src/app
    networks:
      - server
    external_links:
      - client
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - db

  db:
    build: ./db

    environment:
      MYSQL_ROOT_PASSWORD: asdf1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: asdf1234

    ports:
      - 3306
    networks:
      - server

networks:
  server:
    external: true
